[package]
name = "tutorials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ffmpeg = "0.13.3+ffmpeg.6.1"
sdl2 = "0.36.0"